version: '3'

services:

  worker:
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/worker:0.0.0
    restart: unless-stopped
    volumes:
    - /var/run/docker.docker:/sock/var/run.sock
    depends_on:
    - nanny
    stop_grace_period: 5s
    env_file:
    - ./envs/deployment.env

  router:
    container_name: feed_router
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/routing:0.0.0
    restart: unless-stopped
    stop_grace_period: 5s
    env_file:
      - ./envs/deployment.env

  nanny:
    container_name: feed_nanny
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/nanny:0.0.0
    restart: unless-stopped
    volumes:
    - ./config:/home/config
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    environment:
    - NETWORK=feed_platform_default
    env_file:
      - ./envs/deployment.env

  ui-server:
    container_name: feed_ui-server
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/ui-server:0.0.0
    restart: unless-stopped
    volumes:
      - ./envs/:/home/envs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    env_file:
      - ./envs/deployment.env

  summarizer:
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/summarizer:0.0.0
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
    - ./envs/deployment.env

  mapper:
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/mapper:0.0.0
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
    - ./envs/deployment.env

  persistence:
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/persistence:0.0.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
      - ./envs/deployment.env

  feed-admin:
    ports:
      - "80:80"
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}/feed-admin:0.0.0
    restart: unless-stopped
    stop_grace_period: 5s
    env_file:
      - ./envs/deployment.env
    environment:
      - UISERVER=http://ui-server:5000
      - SERVERNAME=feed-admin

