version: '3'

services:

  worker:
    build: ${SOURCE_DIR}/worker
    volumes:
    - /var/run/docker.docker:/sock/var/run.sock
    depends_on:
    - nanny
    stop_grace_period: 5s
    env_file:
    - envs/deployment.env

  router:
    container_name: feed_router
    build: ${SOURCE_DIR}/routing
    ports:
    - "5002:5000"
    stop_grace_period: 5s
    env_file:
      - envs/deployment.env

  nanny:
    container_name: feed_nanny
    build: ${SOURCE_DIR}/nanny
    volumes:
    - ./config:/home/config
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "5003:5000"
    environment:
      BROWSER_BASE_PORT: 4444
    stop_grace_period: 5s
    env_file:
      - ./envs/deployment.env

  ui-server:
    container_name: feed_ui-server
    build: ${SOURCE_DIR}/ui-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./envs:/home/src/config
    ports:
      - "5004:5000"
    env_file:
      - envs/deployment.env

  summarizer:
    build: ${SOURCE_DIR}/summarizer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    environment:
      - TOPICS=results
      - PREFIX=stg
    env_file:
    - envs/deployment.env

  mapper:
    build: ${SOURCE_DIR}/mapper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
    - envs/deployment.env

  persistence:
    build: ${SOURCE_DIR}/persistence
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
      - envs/deployment.env  
  feed-admin:
    ports:
     - "3000:80"
    container_name: feed-admin
    build: ${SOURCE_DIR}/feed-admin
    stop_grace_period: 5s
    environment:
    - UISERVER=http://feed_ui-server:5000
    - SERVERNAME=feed-admin

