# This dockerfile should only require the environment variables DEPLOYMENT_ROOT, SOURCE_DIR, ENV_FILE

version: '3'

services:

  capture-crawler:
    build: ${SOURCE_DIR}/capture-crawler
    volumes:
    - ${SOURCE_DIR}/utils/feed:/usr/capture-crawler/feed
    restart: 'always'
    depends_on:
    - nanny
    stop_grace_period: 5s
    environment:
    - LOG_LEVEL=INFO
    env_file:
    - ${ENV_FILE}

  router:
    container_name: feed_router
    build: ${SOURCE_DIR}/routing
    volumes:   
    - ${SOURCE_DIR}/utils/feed:/home/feed
    ports:
    - "5002:5000"
    stop_grace_period: 5s
    env_file:
      - ${ENV_FILE}

  leader:
    container_name: leader
    build: ${SOURCE_DIR}/leader
    environment:
    - LOG_LEVEL=INFO
    env_file:
    - ${ENV_FILE}
    volumes:
    - ${SOURCE_DIR}/utils/feed:/usr/leader/feed

  nanny:
    container_name: feed_nanny
    build: ${SOURCE_DIR}/nanny
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${SOURCE_DIR}/utils/feed:/home/feed
    ports:
    - "5003:5000"
    stop_grace_period: 5s
    env_file:
    - ${ENV_FILE}

  ui-server:
    container_name: feed_ui-server
    build: ${SOURCE_DIR}/ui-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SOURCE_DIR}/utils/feed:/home/feed
    ports:
      - "5004:5000"
    env_file:
    - ${ENV_FILE}
    environment:
    - AUTHN_SERVER=http://authn:3000
    - JWK_REFRESH_RATE=60
    - AUTHN_AUDIENCE_CHALLENGE=devfeedmachine.local

  summarizer:
    container_name: feed_summarizer
    build: ${SOURCE_DIR}/summarizer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${SOURCE_DIR}/utils/feed:/home/feed
    stop_grace_period: 5s
    environment:
      - TOPICS=results
      - PREFIX=stg
      - LOG_LEVEL=INFO
    env_file:
    - ${ENV_FILE}

  feed-admin:
    ports:
     - "443:443"
    volumes:
     - ${SOURCE_DIR}/feed-admin/certs:/etc/certs
    depends_on:
     - ui-server

    container_name: devfeedmachine.local
    build: ${SOURCE_DIR}/feed-admin
    stop_grace_period: 5s
    environment:
    - UISERVER=http://feed_ui-server:5000
    - SERVERNAME=devfeedmachine.local
    - AUTHSERVER=http://authn:3000
