version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-west-2"
        awslogs-group: "permission-logs"
        awslogs-stream-prefix: "stream"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
    - mongo
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-west-2"
        awslogs-group: "permission-logs"
        awslogs-stream-prefix: "stream"


