version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
    - mongo
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
     - '9092:9092'
     - '29092:29092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="d-sample-queue;d-worker-queue;d-worker-route;d-summarizer-route;d-leader-route"
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_PASSWORDS=feeds,authn
      - POSTGRES_MULTIPLE_USERS=feeds,authn
      - POSTGRES_MULTIPLE_DATABASES=feeds,authn
    volumes:
      - ${DEPLOYMENT_ROOT}/etc/database:/docker-entrypoint-initdb.d

  redis:
    image: redis 

  authn:
    container_name: authn
    image: keratin/authn-server:1.10.0
    ports:
    - "8080:3000"
    environment:
    - AUTHN_URL=http://authn:3000
    - APP_DOMAINS=localhost
    - DATABASE_URL=postgres://authn:authn@database:5432/feeds
    - REDIS_URL=redis://6379/0
    - SECRET_KEY_BASE=changeme
    - HTTP_AUTH_USERNAME=hello
    - HTTP_AUTH_PASSWORD=world 
    depends_on:
    - database
    - redis

