Type: AWS::ECS::Service
Properties: 
  Cluster: feed-cluster 
  DesiredCount: 1
  LaunchType: FARGATE 
  NetworkConfiguration: 
    AwsvpcConfiguration: 
      AssignPublicIp: ENABLED
      subnets:
        - "subnet-036d7436ddca88da3"
        - "subnet-0fe8908adcdca0618"
  PlatformVersion: "LATEST"
  Role: "arn:aws:iam::064106913348:role/FeedAdmin"
  ServiceName: feed-service 
  ServiceRegistries: 
  - ContainerName: feed-admin
    ContainerPort: 3000
    Port: 3000
  ServiceRegistries: 
  - ContainerName: ui-server
    ContainerPort: 5000
    Port: 5000
  - ContainerName: nanny
    ContainerPort: 5000
    Port: 5003
  - ContainerName: router
    ContainerPort: 5000
    Port: 5002 
  - ContainerName: commands
    ContainerPort: 5000
    Port: 5001 
  - ContainerName: database
    ContainerPort: 5432
    Port: 5432
  - ContainerName: kafka
    ContainerPort: 29092
    Port: 29092
  - ContainerName: mongo
    ContainerPort: 27017
    Port: 27017
  - ContainerName: mongo-express
    ContainerPort: 8081
    Port: 8081
  - ContainerName: zookeeper
    ContainerPort: 2181
    Port: 2181
  TaskDefinition: String
