apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leader
  name: leader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leader
  template:

    metadata:
      labels:
        app: leader
    spec:
      imagePullSecrets:
      - name: awsecr-cred 
      containers:
      - env:
        - name: KAFKA_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_ADDRESS
              name: {{ .Values.environment }}
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: {{ .Values.environment }}
        - name: NANNY_HOST
          valueFrom:
            configMapKeyRef:
              key: NANNY_HOST
              name: feedmachine-env
        - name: ROUTER_HOST
          valueFrom:
            configMapKeyRef:
              key: ROUTER_HOST
              name: feedmachine-env
        - name: KAFKA_TOPIC_PREFIX
          valueFrom:
            configMapKeyRef:
              key: KAFKA_TOPIC_PREFIX
              name: {{ .Values.environment }}
        - name: SELENIUM_PORT
          valueFrom:
            configMapKeyRef:
              key: SELENIUM_PORT
              name: feedmachine-env
        image: 064106913348.dkr.ecr.us-west-2.amazonaws.com/feed/leader:0.2.7
        name: leader
        resources: {}
      restartPolicy: Always
