apiVersion: v1
kind: Service
metadata:
  name: authn
  labels:
    service: authn
spec:
  selector:
    app: authn
  type: ClusterIP
  ports:
  - port: {{ .Values.authnServerPort }}
    targetPort: {{ .Values.authnServerPort }}
    protocol: TCP
    name: http
