apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feed-admin
  name: feed-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-admin
  template:
    metadata:
      labels:
        app: feed-admin
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: SERVERNAME
          value: "uatfeedmachine:30000"
        - name: UISERVER
          value: http://ui-server:5000
        - name: NANNYSERVER
          value: http://nanny:5000
        image: 064106913348.dkr.ecr.us-west-2.amazonaws.com/feed/feed-admin:0.2.2
        name: feed-admin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: feed-admin
spec:
  type: LoadBalancer
  selector:
    app: feed-admin
  ports:
  - protocol: "TCP"
    port: 80
    nodePort: 30000
    targetPort: 80
