apiVersion: v1
data:
 {{ .Values.feedAdminHostname }}-key.pem: {{ .Values.feedAdminKey }} # TODO base 64 encoded cert file 
 {{ .Values.feedAdminHostname }}.pem: {{ .Values.feedAdminCert }} # TODO base 64 encoded key file 
kind: Secret
metadata:
 name: feed-admin-ssl
type: Opaque
