
apiVersion: v1
kind: Service
metadata:
  name: feed-admin
spec:
  type: LoadBalancer
  selector:
    app: feed-admin
  ports:
  - protocol: "TCP"
    port: 443
    nodePort: {{ .Values.feedAdminServicePort }}
    targetPort: 443
