apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nanny
  name: nanny
spec:
  replicas: {{ .Values.nannyReplicas }}
  selector:
    matchLabels:
      app: nanny
  template:
    metadata:
      labels:
        app: nanny
    spec:
      imagePullSecrets:
      - name: awsecr-cred 
      containers:
      - name: nanny
        image: {{ .Values.imageRepository }}/{{ .Values.nannyVersion }}
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: FLASK_PORT
          valueFrom:
            configMapKeyRef:
              key: FLASK_PORT
              name: feedmachine-env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: {{ .Values.environment }}-env
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: {{ .Values.environment }}-env
        - name: MONGO_PASS
          valueFrom:
            configMapKeyRef:
              key: MONGO_PASS
              name: {{ .Values.environment }}-env
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOST
              name: {{ .Values.environment }}-env
        - name: CHAIN_DB 
          valueFrom:
            configMapKeyRef:
              key: CHAIN_DB
              name: {{ .Values.environment }}-env
        - name: MONGO_USER
          valueFrom:
            configMapKeyRef:
              key: MONGO_USER
              name: {{ .Values.environment }}-env
        - name: ROUTER_HOST
          valueFrom:
            configMapKeyRef:
              key: ROUTER_HOST
              name: feedmachine-env
        - name: UISERVER_HOST
          valueFrom:
            configMapKeyRef:
              key: UISERVER_HOST
              name: feedmachine-env
        - name: NANNY_HOST
          valueFrom:
            configMapKeyRef:
              key: FLASK_HOST
              name: feedmachine-env

        resources: {}
      restartPolicy: Always
