
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    service: router
spec:
  selector:
    app: router
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
