
apiVersion: v1
data:
  KAFKA_ADDRESS: kafka.services.svc.cluster.local # template
  KAFKA_TOPIC_PREFIX: p # template
  LOG_LEVEL: INFO # template param
  MONGO_HOST: mongo-mongodb-sharded.services.svc.cluster.local:27017 # template param
  DATABASE_HOST: database-postgresql.services.svc.cluster.local
  CHAIN_DB: uat_actionChains # template param
  MONGO_USER: root # secret and template
  DATABASE_USER: feeds
  DATABASE_USER: pass
  MONGO_PASS: {{ .Values.mongoPassword }}
  DATABASE_PORT: "5432" # tempalate
  DATABASE_PORT: "feeds" # tempalate
  DATABASE_NAME: uat_feeds # template 
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: uat-env
  name: uat-env
