
apiVersion: v1
data:
  KAFKA_ADDRESS: kafka.services.svc.cluster.local # template
  KAFKA_TOPIC_PREFIX: u # template
  LOG_LEVEL: INFO # template param
  CHAIN_DB: uat_actionChains # template param
  MONGO_HOST: parameters-mongodb.services.svc.cluster.local:27017
  MONGO_USER:  uat_feeds # secret and template
  MONGO_PASS: {{ .Values.mongoPassword }}
  DATABASE_HOST: database-postgresql.services.svc.cluster.local
  DATABASE_PORT: "5432" # tempalate
  DATABASE_USER: {{ .Values.databaseUser }}
  DATABASE_PASS: {{ .Values.databasePass }}
  DATABASE_NAME: {{ .Values.databaseName }} # template 
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: uat-env
  name: uat-env
