apiVersion: v1
kind: Service
metadata:
  name: ui-server
  labels:
    service: ui-server
spec:
  selector:
    app: ui-server
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
