topics:
  - name: u-sample-queue
    partitions: 1
    replicationFactor: 1
  - name: u-leader-route
    partitions: 1
    replicationFactor: 1
  - name: u-summarizer-route
    partitions: 1 
    replicationFactor: 1
  - name: p-sample-queue
    replicationFactor: 1
    partitions: 1
  - name: p-leader-route
    replicationFactor: 1
    partitions: 2
  - name: p-summarizer-route
    replicationFactor: 1
    partitions: 2
persistence:
  enables: true
prometheus:
  ## Prometheus JMX Exporter: exposes the majority of Kafkas metrics
  jmx:
    enabled: true
    interval: 10s
    ## Timeout at which Prometheus timeouts scrape run, note: only used by Prometheus Operator
    scrapeTimeout: 10s
    ## Port jmx-exporter exposes Prometheus format metrics to scrape
    port: 5556

