topics:
  - name: u-sample-queue
    partitions: 1
    replicationFactor: 1
  - name: u-leader-route
    partitions: 1
    replicationFactor: 1
  - name: u-summarizer-route
    partitions: 1 
    replicationFactor: 1
  - name: p-sample-queue
    replicationFactor: 1
    partitions: 1
  - name: p-leader-route
    replicationFactor: 1
    partitions: 2
  - name: p-summarizer-route
    replicationFactor: 1
    partitions: 2
persistence:
  enables: true
prometheus:
  kafka:
    enabled: true
    interval: 10s
    scrapeTimeout: 10s
    port: 9308
    operator:
      prometheusRule:
        enabled: true
        selector: 
         - app.kubernetes.io/name: prometheus-operator
